---
reporting:
  logging: {}
  metrics: {}
http:
  listen: 0.0.0.0:8081
  profiler: false
clickhouse:
  servers:
    - 127.0.0.1:9000
  database: default
  password: training
  kafka:
    topic: flows
    brokers:
      - 127.0.0.1:9092
    version: 3.6.1
    consumers: 1
  resolutions:
    - interval: 0s
      ttl: 360h0m0s
    - interval: 1m0s
      ttl: 168h0m0s
    - interval: 5m0s
      ttl: 2160h0m0s
    - interval: 1h0m0s
      ttl: 8640h0m0s
  max-partitions: 50
  asns: {}
  networks: {}
  orchestrator-url: ""
kafka:
  topic: flows
  brokers:
    - 127.0.0.1:9092
  version: 3.6.1
  topic-configuration:
    num-partitions: 1
    replication-factor: 1
    config-entries: {}
inlet: !include "inlet.yaml"
console: !include "console.yaml"
#demoexporter: []
