---
# console:
  - reporting:
      logging: {}
      metrics: {}
    http:
      listen: 0.0.0.0:8083
      profiler: false
    default-visualize-options:
      start: 6 hours ago
      end: now
      filter: InIfBoundary = external
      dimensions:
        - SrcAS
    homepage-top-widgets:
      - src-as
      - src-port
      - protocol
      - src-country
      - etype
      - exporter
    clickhouse:
      servers:
        - 127.0.0.1:9000
      database: default
      password: training
    database:
      driver: sqlite
      dsn: /var/lib/akvorado/console.sqlite
