---
# inlet:
  - reporting:
      logging: {}
      metrics: {}
    http:
      listen: 0.0.0.0:8082
      profiler: false
    flow:
      inputs:
        - decoder: netflow
          listen: 0.0.0.0:2055
          type: udp
          workers: 6
        - decoder: sflow
          listen: 0.0.0.0:6343
          type: udp
          workers: 6
      ratelimit: 0
    snmp:
      cache-duration: 30m0s
      cache-refresh: 1h0m0s
      cache-check-interval: 1m0s
      cache-persist-file: /var/lib/akvorado/snmp_cache
      poller-retries: 1
      poller-timeout: 1s
      poller-coalesce: 10
      workers: 10
      # defaultcommunity: training      
      communities:
        ::/0: training      
      security-parameters: {}
    geoip:
      asn-database: /usr/share/GeoIP/GeoLite2-ASN.mmdb
      geo-database: /usr/share/GeoIP/GeoLite2-Country.mmdb
      optional: true
    kafka:
      topic: flows
      brokers:
        - 127.0.0.1:9092
      version: 3.6.1
      flush-interval: 10s
      flush-bytes: 104857599
      max-message-bytes: 1000000
      compression-codec: none
      queue-size: 32
    core:
      override-sampling-rate: 10
      workers: 1
      exporter-classifiers:
        - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
        - ClassifyRegion("Australia")
        - ClassifyTenant("APNIC")
        - ClassifyRole("training")
      interface-classifiers:
        - |
          ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
          ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
          ClassifyExternal()
        - ClassifyConnectivityRegex(Interface.Description,"^(?i)(ge|Gigabit)? ", "$1") &&
          ClassifyInternal()
      # classifiercachesize: 1000
      default-sampling-rate: {}
      asn-providers:
        - flow
        - geoip
